# Site settings
author: NAKISHA RAINBOW
title: WHY I CHOSE SOFTWARE ENGINEERING
header-img: img/home-bg.png
email: kishrenee8307@gmail.com
copyright_name: NAKISHA RAINBOW
description: > # this means to ignore newlines until "baseurl:"
  MY JOURNEY FROM EDUCATION TO TECH
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Krain8307

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
